name: Discussion updated

on:
  discussion:
    types: [created, edited, deleted, pinned, unpinned, labeled, unlabeled]

jobs:
  discussion-updated:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Purge cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        if: success()
        with:
          cf_zone: "a861d89c5932d06f14b2eeb19b818191"
          cf_auth: ${{ secrets.CF_PURGE_API_TOKEN }}
